# Jared-style base Ubuntu image
#
# https://github.com/jaredrhine/docker-play/ubuntu-base-jared-style
#

# Pull base image.
FROM ubuntu:14.04

# Update packages
RUN "apt-get update"

WORKDIR "/tmp"
CMD [ "/bin/bash" ]
